name: Node.js Package

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.0.0'
          registry-url: https://registry.npmjs.org/
      - name: Install npm@9.6.4
        run: npm install -g npm@9.6.4
      - name: Log Node.js version
        run: node -v
      - name: Log npm version
        run: npm -v
      - name: Clean npm cache
        run: npm cache clean --force
      - name: List repository files
        run: ls -la
      - name: Verify package-lock.json existence
        run: test -f package-lock.json && echo "package-lock.json exists" || echo "package-lock.json does not exist"
      - name: Run npm ci
        run: npm ci --verbose
      - name: Build the project
        run: npm run build
      - name: Publish the package
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN_PUBLIC}}
